### ISSUE TITLE
Suggestions don't show up in bottom sheets

### ISSUE THREAD

**Issue by Hadii1** [AbdulRahmanAlHamali/flutter_typeahead#152] opened 2020-01-28 22:36 UTC
Hello, Thank you very much for this great widget. I was trying to use in bottom sheets and suggestions weren't showing up. I'm using  the latest version (1.8.0) and here's a minimal code to copy paste:

```
import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ButtonClass(),
      ),
    );
  }
}

class ButtonClass extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      child: Text(
        'show bottom sheet',
      ),
      onPressed: () {
        Scaffold.of(context).showBottomSheet((_) {
          return SheetWidget();
        });
      },
    );
  }
}

class SheetWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: TypeAheadField(
      textFieldConfiguration: TextFieldConfiguration(
          autofocus: true,
          style: DefaultTextStyle.of(context)
              .style
              .copyWith(fontStyle: FontStyle.italic),
          decoration: InputDecoration(border: OutlineInputBorder())),
      suggestionsCallback: (pattern) {
        return getFakeSuggestions();
      },
      itemBuilder: (context, String number) {
        return ListTile(
          leading: Icon(Icons.shopping_cart),
          title: Text(number),
        );
      },
      onSuggestionSelected: (suggestion) {},
    ));
  }
}

List<String> getFakeSuggestions() {
  return List.generate(25, (index) {
    return index.toString();
  });
}
```

**Comment by kenneth-terraii** [comment] 2020-01-29 12:52
Seems to work fine for me?
![Screenshot_1580302288](https://user-images.githubusercontent.com/57580895/73358270-3ddcc080-426c-11ea-9c3a-a24f87cbd774.png)

**Comment by KaYBlitZ** [comment] 2020-01-29 12:53
Hi, it seems to work fine.
![Screenshot_1580302288](https://user-images.githubusercontent.com/5499214/73358358-72e91300-426c-11ea-8453-837ae91f57fe.png)

**Comment by Hadii1** [comment] 2020-01-29 14:37
I was trying the code on an iphone 11 pro max emulator , I tried it again on a pixel 3 android emulator and it seemed to work. maybe the issue is iOS specific?

**Comment by TimWhiting** [comment] 2020-01-30 01:53
I've been able to reproduce this issue on web / desktop. 

The issue is that the suggestionsBox only updates it's size and offset when the widget is first built, when the keyboard is displayed, window is resized, or scroll position changes. 

This misses the case when none of those things happen, but the location has changed. 

For example on web / desktop the virtual keyboard doesn't pop up when the field obtains focus. And when that happens in a bottomSheet, then the only time the suggestions box has updated it's size and offset is when the widget was first built (i.e. when the bottomSheet started scrolling up from the bottom of the screen). At that point the bottom sheet has almost no size, and so the max size of the suggestionsBox is calculated to be something close to zero. 

There is no prebuilt widget for notifying a child when the location has changed so I came up with one that closely models the Flutter framework's SizeChangedLayoutNotifier which notifies a child when the size has changed. I modified it to do the same but for location changes. However, the code is not as clean as I'd like to have it before submitting a pull request & I have to catch an exception for some reason. But you can look at my changes here: `https://github.com/TimWhiting/flutter_typeahead/blob/master/lib/flutter_typeahead.dart`.

**Comment by Hadii1** [comment] 2020-01-31 14:21
@TimWhiting  Thanks for the insight . I'm delaying the widget first build now manually with a future.delayed and it does show the suggestions. Ugly but it works for now until a later fix.

**Comment by TimWhiting** [comment] 2020-02-02 00:12
A future.delayed was my initial approach as well to validate the issue. It definitely needs to be fixed in the library as well. I just pushed an update to my branch that just resizes the box every time the overlay gets built. It's probably not super performant, but it works. @AbdulRahmanAlHamali what are your thoughts on this issue?

**Comment by BenevidesLecontes** [comment] 2020-03-01 19:50
@Hadii1 I can confirm, it doesn't work on ios, works on android.

**Comment by fbasilico** [comment] 2020-06-05 19:40
The CupertinoTypeAheadField is not working using  showCupertinoModalPopup

**Comment by DanielTheProgrammer** [comment] 2022-10-14 22:18
Two years later, still doesn't work

**Closed** 2023-01-28 18:35 UTC
