### ISSUE TITLE
[Feature] Hide dropdown in certain contexts

### ISSUE THREAD

**Issue by darkfrog26** [AbdulRahmanAlHamali/flutter_typeahead#563] opened 2024-01-27 03:11 UTC
### Use case

I'm using this module to provide context-based results, so under certain circumstances, I don't want the dropdown to appear at all. If I return an empty List, it says no results but still shows the dropdown.

### Proposal

If `null` was a valid response for `suggestionsCallback` it would offer a convenient way to specify that no dropdown should appear.

**Comment by clragon** [comment] 2024-01-27 03:28
Duplicate of #560

**Closed by clragon** 2024-01-27 03:28 UTC
Labels: enhancement
