### ISSUE TITLE
How can we enable keyboard arrow up and down keys to scroll down or up in textfield suggestion list in flutter web?

### ISSUE THREAD

**Issue by techttiru** [AbdulRahmanAlHamali/flutter_typeahead#423] opened 2022-08-31 18:40 UTC
how can we enable keyboard arrow down and up keys for scrolling the textfield suggestion scrolling in flutter web? I am using TypeAheadFormField widget to show suggestion when user type character in text field and scrolling works when we use mouse. but i want to scroll this suggestion list using keyboard arrow keys. how can we do this? any input would be really appreciated.

**Comment by flutter-painter** [comment] 2022-11-09 00:16
duplicate of https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/298

**Comment by sarbogast** [comment] 2023-05-20 03:58
That would be an awesome feature indeed

**Comment by selvam920** [comment] 2023-06-26 07:34
any update on this?

**Comment by jobypthomas** [comment] 2023-11-10 12:03
any update?

**Closed** 2023-11-26 16:59 UTC
