### ISSUE TITLE
hideSuggestionsOnKeyboardHide not working on iOS

### ISSUE THREAD

**Issue by davbaron** [AbdulRahmanAlHamali/flutter_typeahead#127] opened 2019-10-13 05:04 UTC
I have been investigating your excellent add-in for use in my Flutter app. I have built a generic 'pick value' screen which resembles your examples to some extent (no 'form' involved). All works great except for the 'hideSuggestionsOnKeyboardHide', but only on iOS. I develop on both a Mac and on Windows. On my Mac, I 'test' via the iOS simulator. When configured to *not* use the hardware keyboard, and with 'hideSuggestionsOnKeyboardHide' set to false, the suggestion list is hidden when the 'Done' button is clicked on the iOS keyboard. On my Win 10 laptop I test with a physical device (OnePlus 3) and it seems to work correctly, i.e., clicking on the 'back' button on the phone hides the keyboard, but not the suggestions list (which grows to fill in all newly available space).

There is not much technique involved here, so I'm not sure if you need to see any code or not. My guess would be that the 3rd party add-in that you are using (keyboard_visibility.dart) is not providing you the event on iOS, but I have not downloaded your code to try to find out.

Is anyone else having issues with this feature, especially on iOS?

Thank you and keep up the great work.

**Comment by KaYBlitZ** [comment] 2019-10-16 13:42
Hi, I just updated the keyboard visibility dependency as suggested by another one of our users. This one should include a variety of fixes. Can you try typeahead 1.7.0 to see whether this fixes your issue?

**Comment by davbaron** [comment] 2019-10-16 14:56
I updated my pubspec.yaml to ^1.7.0 and stopped/re-started (re-compiled) my demo app.  There was no difference in behavior. Upon tapping the 'Done' button on the iOS simulator keyboard, the overlay is removed/hidden. Upon giving focus (tapping within) the typeahead text field, the overlay reappears (along with the keyboard).

**Comment by KaYBlitZ** [comment] 2019-10-16 17:41
Hmmm. Unfortunately this difference in behavior is not a bug in the code. Currently TypeAhead works by showing suggestions if the textfield has focus. Whenever the textfield loses focus, the suggestions box is hidden, no exceptions. You can actually mimic this same behavior by hitting the check button on the keyboard instead of the back button on Android. This causes the textfield to lose focus and hide the suggestions. AFAIK there is no way to hide the keyboard in iOS without losing focus.

We can have the suggestions box not close when losing focus, but this presents a problem for hardware keyboard users and would require manual closing of the suggestions box via an X button or requiring the user to select a suggestion. That is definitely not ideal I believe.

I do not see an easy solution for this. Do you think you can work with this behavior difference?

**Comment by davbaron** [comment] 2019-10-16 18:52
I understand your comments. That said, the behavior (most likely Flutter-produced) is different on iOS than on Android. On iOS, yes, the focus on the field is lost upon hitting the Done button, resulting in you hiding the suggestions list. On Android, tapping the 'back' button on the phone results in the keyboard closing, *but* the field maintaining focus, which results in your code keeping the suggestions list open. My *guess* is that the iOS behavior is due to something Flutter is doing, versus something that you are doing. 

Regardless, I seem to have 'fixed' (or more appropriately 'worked around') this by adding the following to my TypeAheadField def:
```
onSubmitted: (value){
    new Future.delayed(Duration(milliseconds: 100),() {
        _suggsController.open();
    });
},
```
Now on iOS clicking the Done button results in the list showing back up again, even though the text field has no focus. I had to have the delay in there, otherwise it would not work. On Android, clicking the 'return' key does not produce a 'submit' event, so the hideSuggestionsOnKeyboardHide = false 'works' in this case, and the list remains on-screen. If the Android keyboard includes a 'Done' button, then tapping it *does* result in a loss of focus for the field, however the submit event *is* generated, and the above code kicks in nicely.

As for 'manually' closing the list, my current UX has the list being displayed on a completely separate screen from my 'input form', and that screen includes an explicit 'Cancel' button, which, when tapped, tells the suggestion list controller to close() the overlay. If the UX were to change to a form-based usage (with no explicit 'close list' widget), then yes, things could get dicey.

I imagine this issue can be closed, as this is most likely out of your control.

Thanks again for your help here... these types of widgets are very complex and can be 'never ending' in their complexity and problem generation.

-David

**Closed** 2020-01-23 15:12 UTC
