### ISSUE TITLE
suggestionsCallback do not fire on focuses on TextFormField [Bug] 

### ISSUE THREAD

**Issue by Aa11220** [AbdulRahmanAlHamali/flutter_typeahead#566] opened 2024-02-02 20:46 UTC
### Steps to reproduce

if you have depend on another value to select list in suggestion you can not change unless you write and delete on the TextFormField 

### Expected results

on click of TextFormField  it fire suggestionsCallback to get the right list 

### Actual results

it fires after change the value of TextFormField 

### Package Version

 5.1.0 

### Platform

Android

### Code sample

<details open>
<summary>Code sample</summary>

```dart
ypeAheadField<ClaimForEmpModule>(
                    suggestionsCallback: (search) async {
                      print("on work");
                      if (empname.text.isEmpty) {
                        print("list is empty");
                        return [];
                      } else {
                        final _res = await ClaimsForEmp.getClaims(empid ?? 1);
                        if (_res is successed) {
                          onSuccessclaims =
                              _res.result as List<ClaimForEmpModule>;
                          return onSuccessclaims.where((element) {
                            return element.reference
                                .toLowerCase()
                                .contains(search.toLowerCase());
                          }).toList();
                        } else {
                          print("error");

                          return [];
                        }
                      }
                    },
                    focusNode: calimsFocuseNode,
                    controller: claimscontroller,
                    builder: (context, controller, focusNode) {
                      return TextFormField(
                        validator: (value) {
                          if (value == null || value.isEmpty) {
                            return 'Please select employee name';
                          } else if (onSuccessclaims
                              .any((element) => element.reference == value)) {
                            return "Enter  Name already exist";
                          }
                          return null;
                        },
                        style: new TextStyle(
                          fontSize: MediaQuery.of(context).size.height * .02,
                        ),
                        controller: controller,
                        focusNode: focusNode,
                        autofocus: false,
                        decoration: InputDecoration(
                          hintText: "claims",
                          filled: true,
                          fillColor: Colors.white,
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(15),
                            borderSide:
                                BorderSide(width: 1, color: bordercolor),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(15),
                            borderSide:
                                BorderSide(width: 1, color: bordercolor),
                          ),
                        ),
                      );
                    },
                    itemBuilder: (context, value) {
                      return ListTile(
                        title: Text(value.reference),
                      );
                    },
                    onSelected: (value) {
                      print(value.reference);
                    },
                  ),
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by clragon** [comment] 2024-02-02 21:32
Duplicate of #561

**Closed by clragon** 2024-02-02 21:32 UTC
Labels: bug
