### ISSUE TITLE
Flutter 3.7 Taps not working in the selection overlay when Accessibility features are ON

### ISSUE THREAD

**Issue by davidmartos96** [AbdulRahmanAlHamali/flutter_typeahead#463] opened 2023-02-20 09:16 UTC
Hello!
I've recently encountered with an issue where the taps in the suggestion box are not working (tapping closes the menu instead of tapping an item) when accessibility features on the device are on. 
I have tried with "Select to Speak", but I believe it has similar issues with VoiceOver and TalkBack.

I've found that the problem is in this piece of the code.

![image](https://user-images.githubusercontent.com/22084723/220062304-12c5d532-98a4-4fa9-bce2-83a0aa8b35f0.png)

When it is `true` and the accessibility options are on in the device, it will trigger the issue on Flutter 3.7 (not in 3.3). I can only trigger it by activating the feature on the device. Simply returning the Semantics widget always doesn't reproduce it.

I believe this can also trigger when more "lightweight" accessibility options are on or special keyboard functionality by certain manufacturers is on. I had reports from a few Pixel users and some Samsung, which stated that they don't have accessibility options turned on and they were experiencing this issue. Deploying a version without the Semantics if branch has fixed the issue for them. 

Version tested flutter_typeahead 4.3.6

**Comment by ivofernandes** [comment] 2023-02-20 12:00
A great way to make the package evolve is to improve the package example, do you have an widget class with the example that uses semantics and reproduces this problem?

**Comment by davidmartos96** [comment] 2023-02-20 12:26
@ivofernandes The example app in the repository can reproduce it. For instance the second tab. Type a letter, and you cannot tap a city suggestion nor scroll the suggestions. (with the accessibility options on)

**Comment by sjmcdowall** [comment] 2023-02-26 14:54
I no longer actually maintain the code -- just a merge monkey for this -- so we'll need someone to dig into this and see if its a Flutter issue or typeahead .. and if the later a fix and a test case in the test library.

**Comment by mdmota** [comment] 2023-03-01 20:14
to fix do I have to change something in the code or just update the plugin to the latest version?

**Comment by emersion** [comment] 2023-03-02 16:19
Nobody has found a fix for this issue yet.

**Comment by clragon** [comment] 2023-03-03 11:00
Hacking the issue away in my app by simply disabling accessibility:
```dart
MediaQuery(
  // Temporary fix for https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463
  data: MediaQuery.of(context).copyWith(
    accessibleNavigation: false,
  ),
  child: TypeAheadField<T>(
```
since I am getting reports from people with false positives on certain devices.
No idea how this could be fixed in the long term though.

If weird manifacturer changes lead to this boolean being erronously set, how would we detect it? 
Maybe the framework itself or even the OS itself would have to do some adjustments.

**Comment by sjmcdowall** [comment] 2023-03-03 15:23
Someone posted a work around on this issue I guess on another issue :). I don't remember but he wrapped the stuff around something else and it worked .. but not sure if it works for all conditions on all devices .. maybe you can find that solution @clragon and see??  And yes, I know the above wasn't very. helpful but it's in the issues list near the top I think

**Comment by SittiphanSittisak** [comment] 2023-03-04 14:00
> ```dart
> MediaQuery(
>   // Temporary fix for https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463
>   data: MediaQuery.of(context).copyWith(
>     accessibleNavigation: false,
>   ),
>   child: TypeAheadField<T>(
> ```

not work for me T_T.

**Comment by clragon** [comment] 2023-03-08 22:29
Turns out I was too quick with my hack.

It won't work because the `TypeAheadField` suggestions box is inside of a `Overlay`, which isnt a child of the Widget which `TypeAheadField` is a child of.

To "fix" this hack we would therefore have to place the `MediaQuery` override above the `Overlay` used by `TypeAheadField`, which is most likely going to be the one by the root `Navigator`.
Thus, we have to disable `accessibleNavigation` "globally".

I therefore now use this:

```dart
MaterialApp(
  builder: (context, child) => MediaQuery(
    // Temporary fix for https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463
    data: MediaQuery.of(context).copyWith(
      accessibleNavigation: false,
    ),
    child: child!,
  ),
),
```

I made sure to test it this time.

**Comment by mdmota** [comment] 2023-03-14 01:23
I didn't think it was cool. Will it take away the accessibility of the entire app? and the user who wants to use accessibility?

**Comment by sjmcdowall** [comment] 2023-03-19 17:26
yeah -- I mean -- it seems like a hack. Still looking for someone to find the real underlying issue and fix it ..

**Comment by GustavoFigueira** [comment] 2023-03-23 22:23
Yeah, problem also happens on my device (running the package example) :(

Tested on a **REALME 8 Pro (RMX3081)**, **Android 12**.

If anyone finds a solution, please let us know...
Meanwhile I'll try to debug the package code and try to find a solution too.

**Comment by GustavoFigueira** [comment] 2023-03-23 22:58
**I can confirm** that the problem is in the **Accessibility section!**

<img width="150" alt="1" src="https://user-images.githubusercontent.com/15182680/227382725-3546f23f-e351-4d3c-b182-fd0ae7535410.png">
<img width="150" alt="2" src="https://user-images.githubusercontent.com/15182680/227382740-63421d13-1486-4d56-8c72-04f8be50c7b5.png">
<img width="150" alt="3" src="https://user-images.githubusercontent.com/15182680/227382747-89eb57a4-c567-43de-b0e8-709135b1c694.png">

In my case, I have the **Anydesk** app that has these permissions enabled.
Disabling as in the image, it works like a charm!

**Comment by Mecharyry** [comment] 2023-04-04 10:40
Similar to what @GustavoFigueira said, this happens because some apps require accessibility to be enabled for them, some password managers, or internet security. When these are enabled the `MediaQuery.accessibleNavigation` is erroneously reporting as true, but technically the user isn't using an accessibility service that is associated with navigation e.g. talkBack, switches etc.

I posted about this in an associated closed issue [here](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/475). 

I don't know if anyone has opened an issue with the flutter team, but it is probably something they should be aware of.

**Comment by Mecharyry** [comment] 2023-04-04 11:47
I've done a bit more digging and I actually think it might be the usage of `CompositedTransformFollower` that is causing the issue. Here I have a before, where I am using the `CompositedTransformFollower`. After shows it removed, directly using `suggestionsList` [here](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/master/lib/src/material/field/typeahead_field.dart#L833). When looking at before, you can see that it is only allow selection of the first 2 items, which tipped me off that it might not be related to the Semantics. I've also not experienced any other problems with Semantics in my personal apps. 

Unfortunately I don't have enough details of how the `CompositedTransformFollower` works to offer a fix to the problem. 

| Using CompositedTransformFollower | Dropping CompositedTransformFollower |
| --- | --- |
https://user-images.githubusercontent.com/3380092/229781860-1b4c81f1-213e-4c3e-b444-d4e7ea839cc7.mp4 | https://user-images.githubusercontent.com/3380092/229781939-e85d1ee9-c2fc-4aa9-9267-8ceea7375b38.mp4

**Comment by robcleghorn** [comment] 2023-04-05 10:32
Thanks for the discovery @Mecharyry and @GustavoFigueira I have a similar issue where this is causing problems, was the accessibility setting for a password app.  Happens on Android 11 and 13.

**Comment by TheCarpetMerchant** [comment] 2023-07-03 19:48
Just made a pull request #509 to implement's @clragon 's solution in just the needed place.
If other people could confirm the issue does get fix in every case, try it directly with :
```
  flutter_typeahead:
    git:
      url: https://github.com/TheCarpetMerchant/flutter_typeahead
      ref: aabb57104ace33a25a950de1c4780433b14b84d5
```

**Comment by sebastianbuechler** [comment] 2023-07-10 15:39
> Just made a pull request #509 to implement's @clragon 's solution in just the needed place. If other people could confirm the issue does get fix in every case, try it directly with :
> 
> ```
>   flutter_typeahead:
>     git:
>       url: https://github.com/TheCarpetMerchant/flutter_typeahead
>       ref: aabb57104ace33a25a950de1c4780433b14b84d5
> ```

I can confirm that this fixes the issue (even though it's more of a hack). Also, I only observed the issue when running on android 13 with enabled accessibility apps like 1password or bitdefender.

**Comment by VladPetruM** [comment] 2023-07-11 21:02
Same problem with Android 13. After applying the above fix, the overlay captured the tap gesture.

**Comment by CesareIsHere** [comment] 2023-10-10 19:25
@TheCarpetMerchant I just saw the the PR hasn't been merged . I'm still having the problem and i finally fixed it using @clragon solution. Please everyone, let's try to revive this issue and merge the solution.

**Comment by TheCarpetMerchant** [comment] 2023-10-10 19:32
@CesareIsHere The fix was merged. Read the PR I mentionned

**Comment by CesareIsHere** [comment] 2023-10-10 19:39
Just seen that the default value of ignoreAccessibleNavigation is false, thank you!

**Closed** 2023-11-26 16:56 UTC
