### ISSUE TITLE
MR 45 Hide the suggestions box when keyboard is hidden

### ISSUE THREAD

**Issue by anslex** [AbdulRahmanAlHamali/flutter_typeahead#48] opened 2019-02-20 05:38 UTC
Hello,

I get a closing keyboard immediately after this change on a closed keyboard:
E/SpannableStringBuilder( 9947): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

I tap on the entry field, keyboard opens and closes and I get an error. This issue appeared with this new change.

OS: Android 7.1.1
 Flutter version 1.2.0

**Comment by KaYBlitZ** [comment] 2019-02-20 12:00
Hi, can you post some minimal sample code that causes this error? I want to
reproduce it to see what is happening exactly. For now, you can use the
previous version of 1.0.2 in your pubspec until this gets resolved.

**Comment by sjmcdowall** [comment] 2019-02-20 12:53
Also what platform (iOS/Android) and steps to reproduce -- 

Also maybe your full code -- maybe something else in the Widget tree is interfering ??

**Comment by KaYBlitZ** [comment] 2019-02-20 19:36
@sjmcdowall I just took a look at the code again. I didn't test my code fully and it's causing all these issues. I just realized that if the user is using a hardware keyboard, they will not even be able to type because the code will not detect a keyboard and unfocus the focusnode. Not sure what the root cause is for these other issues people are having, but the problem code either has to be removed or changed.

It doesn't seem possible at all to detect keyboard state changes entirely in flutter code (which is what I tried doing & why we are having these issues), so we will have to use that [3rd party library](https://github.com/adee42/flutter_keyboard_visibility) which uses native code for detection.

What do you think?

**Comment by sjmcdowall** [comment] 2019-02-20 21:23
OK -- let's use the 3rd party .. now.. how do I UNPUBLISH something .. doh! 

Guess I need to get the master @ 1.0.2 and then publish again ..

**Comment by KaYBlitZ** [comment] 2019-02-20 22:09
I am going to let @AbdulRahmanAlHamali decide whether to proceed with using the 3rd party or not. It's a pretty big change.

**Comment by sjmcdowall** [comment] 2019-02-20 22:36
If we don't use the 3rd party -- how are we going to fix the issue?

**Comment by AbdulRahmanAlHamali** [comment] 2019-02-24 01:24
Hello guys

Sorry for taking this long to reply. Thank you for all the hard work that you have been doing. The package would definitely be dead without your help!

Regarding the 3rd party library. I don't mind using it as long as:

1- It is good, stable, and solves the problem at hand.
2- It does not include other unneeded dependencies that we are not sure why they are there.
3- We lock the dependency to a specific version, and only upgrade to a newer version after making sure the newer version does not break our code.

So if that plugin solves the keyboard problem, which has been a huge pain in a variety of ways, then I say let's definitely go for it!

**Comment by KaYBlitZ** [comment] 2019-03-01 16:40
I am working on incorporating the 3rd party library now and seeing if I can fix various other issues. Closing because the offending code has been removed.

**Closed by KaYBlitZ** 2019-03-01 16:40 UTC
