### ISSUE TITLE
[Feature] Add

### ISSUE THREAD

**Issue by q384264619** [AbdulRahmanAlHamali/flutter_typeahead#611] opened 2024-12-09 03:11 UTC
### Use case

![企业微信20241209-110437](https://github.com/user-attachments/assets/3b6820a3-268d-4b9d-9ace-37eeb93db4ac)

### Proposal

1.I hope the content display width of Lenovo can break through the limit of the input box and fill the full screen width for display
2.I found that in the original code, I only need to change the Floater's followWidth property to false to achieve the desired effect. I hope the author can make it public
![企业微信20241209-110838](https://github.com/user-attachments/assets/66eeb082-2db7-433e-9d99-187a95dfe094)
![企业微信20241209-111050](https://github.com/user-attachments/assets/b452b535-9f2b-4379-a9ab-58896d4d1028)

**Comment by clragon** [comment] 2024-12-12 16:59
Duplicate of #577

**Closed by clragon** 2024-12-12 16:59 UTC
Labels: enhancement
