### ISSUE TITLE
suggestionsCallback not being called iOS

### ISSUE THREAD

**Issue by jan1za** [AbdulRahmanAlHamali/flutter_typeahead#57] opened 2019-02-26 07:06 UTC
Version flutter_typeahead: ^1.0.5 works perfectly on Android, however the suggestionsCallback is not being fired on iOS.

Currently running minimum iOS build 10.
Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D10)
xCode version Version 10.1 (10B61)

I have upgraded flutter, reinstalled the pods. I have not attempted to debug the issue yet, except that the suggestionsCallback is not firing.

**Comment by jan1za** [comment] 2019-02-26 07:22
I have checked out your lasted code and tried it, it does not work there either.

PS Thank you for a very cool plugin.

**Comment by jan1za** [comment] 2019-02-26 07:35
Sorry, it was my fault, I wanted to set an initial value, however I updated the controller and it does not work in iOS, so this is not a defect.
To simulate 
```
TextFieldConfiguration(
        controller: TextEditingController(text: initialValue),

```

**Comment by jan1za** [comment] 2019-02-26 08:51
I have re-opened this because setting the controller on the TextFieldConfiguration results in the suggestionsCallback not being called in iOS

**Comment by jan1za** [comment] 2019-02-26 09:39
Your code is working in your example. I have two type ahead controls. However, I am going to close this because it is working in your example

**Comment by sjmcdowall** [comment] 2019-02-26 12:50
I use iOS all the time and don't have any issues but -- I confess I'm not trying to do what you are doing. :)  Can you post a small example program that reproduces the issue .. it maybe due to the 2 Typeaheads in the Widget Tree (although not sure why) .. but maybe the use of the TextController isn't quite right .. and I will tell you doing Focus properly on iOS and multiple Text Fields is a tricky subject that causes all sorts of side effects.

Anyway, if you want to post a small working example (starting with maybe the simple flutter create and going from there) and letting us know where it is I can take a deeper look ... 

Cheers!

**Comment by jan1za** [comment] 2019-02-26 13:08
@sjmcdowall it has something to do with memory management between android and ios, if the controller is created as follows:
TextFieldConfiguration(
        controller: TextEditingController(text: initialValue),

Then it does not work iOS, but works in Android, however if it is created in a stateful widget, and the TextEditingController is created as final as you have done in your example it works. No idea why. I tried debugging it, but in iOS the listener is never fired, in android it works. However, as mentioned if it is final outside of the build process (ie created once) it works no problem.

Thank you again for a cool plugin.

**Comment by sjmcdowall** [comment] 2019-02-26 13:17
Ahh -- interesting.  From everything I've ever done and read -- I've ALWAYS used a Controller in a Stateful widget where I initialize it in initState() and make sure I dispose of it in dispose() else memory management is not good.   

I'm not sure "final" is key here .. as long as it gets initialized for the proper high level widget and disposed correctly .. 

Sounds like you are on the right track to making it work though .. and I don't think this is a TypeAhead issue per se, as I bet if you coded the same idea as normal TextField widgets you may get the same results? 

I am going to close this for now .. you can always re-open it if there is more to the story. 

Cheers

**Closed by sjmcdowall** 2019-02-26 13:17 UTC

**Comment by jan1za** [comment] 2019-02-26 13:19
@sjmcdowall I totally agree. Seems to be how Android uses mem versus iOS. Thank you for the support!

**Comment by jan1za** [comment] 2019-02-26 13:19
Sorry I thought I closed it :/ my bad :)
