### ISSUE TITLE
Flutter Type Ahead | Movement with Arrow Keys | Flutter Desktop / Web

### ISSUE THREAD

**Issue by NiranjanShah** [AbdulRahmanAlHamali/flutter_typeahead#320] opened 2021-06-08 17:32 UTC
Any plans to support arrow keys, i.e moving  entry up in the suggestion list when user presses Up arrow key and same for other navigation keys of the Hardware keyboard.

The package will be quite useful for Flutter Desktop & Web Application, if the hardware navigation keys are supported.

**Comment by debjeetproso** [comment] 2022-09-23 06:00
but typeahead doesnot support for web/desktop

**Comment by flutter-painter** [comment] 2022-11-09 00:15
duplicate of https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/298

**Closed** 2023-01-28 18:38 UTC
