### ISSUE TITLE
Not working on Safari flutter 2.10.0

### ISSUE THREAD

**Issue by rutaba1** [AbdulRahmanAlHamali/flutter_typeahead#375] opened 2022-02-11 21:00 UTC
Hi, recently I upgraded to flutter 2.10.0 and before that typeahead was working fine on Safari. But now I can not type text in the TypeAheadFormField.

**Comment by djol** [comment] 2022-02-14 06:05
Same situation for me after upgrading to Flutter 2.10.0.

`Flutter 2.10.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fdd0af78bb (3 weeks ago) • 2022-01-25 22:01:33 -0600
Engine • revision 5ac30ef0c7
Tools • Dart 2.16.0 (build 2.16.0-134.5.beta) • DevTools 2.9.2`

`flutter_typeahead version 3.1.4`

Works perfectly on Chrome and Firefox, but on Safari 15.3 (Mac OS 12.2) the TypeAheadFormField will not accept any keyboard input. The field accepts focus and a cursor appears, but nothing appears in the field and no suggestionsCallback is called.

Standard Flutter TextFormField's on the same page work and behave normally.

The Safari behaviour occurs both in development and in an instance deployed to Firebase hosting.

I'm not sure how to debug further as no console errors appear in Safari's js console.

**Comment by djol** [comment] 2022-02-17 06:41
Good news @rutaba1 - this issue was identified as [Flutter #96411](https://github.com/flutter/flutter/issues/96411) for 2.10 and has been **fixed in beta, 2.11.0-0.1.pre**.

Go do a `flutter upgrade` to get this goodness! I just upgraded and confirmed the problem is fixed in both my dev system and in production when deployed to firebase.

**Comment by Ahmadre** [comment] 2023-01-25 15:06
> Good news @rutaba1 - this issue was identified as [Flutter #96411](https://github.com/flutter/flutter/issues/96411) for 2.10 and has been **fixed in beta, 2.11.0-0.1.pre**.
> 
> Go do a `flutter upgrade` to get this goodness! I just upgraded and confirmed the problem is fixed in both my dev system and in production when deployed to firebase.

still not working on Flutter 3.7.0....

**Comment by djol** [comment] 2023-01-26 04:56
No, it has been working from Flutter 2.10 to 3.3.

Now in 3.7 there is a new, different issue related to `onSuggestionSelected` not being called (as per #446).

**Closed** 2023-01-28 18:42 UTC
