### ISSUE TITLE
Make SuggestionBox can be on top of TextField.

### ISSUE THREAD

**Issue by yohom** [AbdulRahmanAlHamali/flutter_typeahead#9] opened 2018-10-16 06:21 UTC
Is there any way to put the `SuggestionBox` above `TextField`? Because now my situation is that the input method will block the SuggestionBox, so I want to make the SuggestionBox above the TextField.

**Comment by AbdulRahmanAlHamali** [comment] 2018-10-16 07:41
Hey,

So you want to show the suggestions to the top instead of the bottom, depending on how much visible space there is? or depending on what exactly?

**Comment by yohom** [comment] 2018-10-16 07:56
Yeah, except the `SuggestionBox`'s location and growth direction(up instead of down) are different, other features should be the same as the current ones. I feel like the whole point of this function is to fix the bottom of the ListView and grow it up. Do you have any ideas?

**Comment by AbdulRahmanAlHamali** [comment] 2018-10-16 07:59
Thank you for the suggestion! This is a nice feature to have.

This might take me some time to implement as I am a bit busy these few days. If you're in a hurry, you can implement it and submit a pull request :) Otherwise, I will try to implement it as soon as possible.

**Comment by yohom** [comment] 2018-10-16 08:05
Thank you. I will try to implement it.

**Comment by Rassell** [comment] 2019-01-07 14:20
Updated pull request here:

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/20

**Comment by KaYBlitZ** [comment] 2019-01-20 21:11
I tested @Rassell 's version and found a few weird behaviors. Using
```
noResize: false, direction: AxisDirection.up,
```
the most relevant search is at the top of the suggestions box. Not sure if this is the intended behavior or if the list should be reversed, ie: most relevant object at bottom of box and least relevant going up. I believe the list should be reversed since the direction is up.

I also tried
```
noResize: true, direction: AxisDirection.up,
```
but the list goes down instead of up.

Also if the keyboard is covering the TextBox, the list does not go up and instead is not shown at all.

I think most of these breaking changes came from when I implemented the auto-resize and scrolling fixes.
To be sure, I tested @yohom 's original fork and found that it grows up, but does not scroll. This comes from the original problem that I fixed where the entire list is being shown so scrolling isn't possible.

It's a good start, but there needs to be more fixes so it meshes well with the breaking changes that I have made.

**Comment by KaYBlitZ** [comment] 2019-01-21 04:19
@Rassell @yohom If you guys have time, can you test my fork for the up direction functionaliy? I modified the code from your PRs to work with the auto-resize feature I added before. This way we do not have to add a noResize attribute and it will just work. In pubspec.yaml use:
```
flutter_typeahead:
    git: 'https://github.com/KaYBlitZ/flutter_typeahead.git'
```

**Comment by KaYBlitZ** [comment] 2019-01-23 15:17
I committed to master. Someone just has to push to the pub @sjmcdowall  @AbdulRahmanAlHamali . I also added my email in pubspec.yaml if you want to give me access.

Let us know if anyone finds an issue with the direction property.

**Closed by KaYBlitZ** 2019-01-23 15:17 UTC

**Comment by sjmcdowall** [comment] 2019-01-23 17:13
Great -- I'll do that when I get home --

**Comment by sjmcdowall** [comment] 2019-01-24 00:39
pushed
