### ISSUE TITLE
Build Failed flutter 3.10.0

### ISSUE THREAD

**Issue by Soumyajeet1992** [AbdulRahmanAlHamali/flutter_typeahead#491] opened 2023-05-22 08:11 UTC
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\URI\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_keyboard_visibility-5.4.3\android\build.gradle' line: 37

* What went wrong:
A problem occurred evaluating project ':flutter_keyboard_visibility'.
> Could not find method disable() for arguments [InvalidPackage] on task ':flutter_keyboard_visibility:lint' of type com.android.build.gradle.tasks.LintGlobalTask.

**Comment by Soumyajeet1992** [comment] 2023-05-22 12:54
@AbdulRahmanAlHamali any help will be appreciated

**Comment by Soumyajeet1992** [comment] 2023-05-22 12:59
@sjmcdowall

**Comment by sjmcdowall** [comment] 2023-05-22 14:00
This is a duplicate of 490...

**Closed as completed by sjmcdowall** 2023-05-22 14:00 UTC
